apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cartiva-dev

resources:
  - ../../base

namePrefix: dev-

patches:
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
      name: cartiva-config

commonLabels:
  environment: development
