apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartiva-api
spec:
  replicas: 4
  template:
    spec:
      containers:
        - name: cartiva-app
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 2Gi
