apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cartiva-prod

resources:
  - ../../base

namePrefix: prod-

patches:
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
      name: cartiva-config
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: cartiva-api

commonLabels:
  environment: production
