apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cartiva-ingress
  namespace: cartiva
  labels:
    app.kubernetes.io/name: cartiva-ingress
    app.kubernetes.io/part-of: cartiva-mall
  annotations:
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/proxy-body-size: '10m'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '60'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '60'
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Frame-Options: SAMEORIGIN";
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "X-XSS-Protection: 1; mode=block";
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - cartiva.mall
        - api.cartiva.mall
      secretName: cartiva-tls-certs
  rules:
    - host: cartiva.mall
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cartiva-api
                port:
                  number: 5001
    - host: api.cartiva.mall
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cartiva-api
                port:
                  number: 5001
