apiVersion: v1
kind: Secret
metadata:
  name: cartiva-secrets
  namespace: cartiva
  labels:
    app.kubernetes.io/name: cartiva-secrets
    app.kubernetes.io/part-of: cartiva-mall
type: Opaque
stringData:
  MONGODB_URI: 'mongodb://mongodb-service:27017/cartiva'
  REDIS_URL: 'redis://redis-service:6379'
  JWT_ACCESS_SECRET: 'placeholder-jwt-access-secret-min-32-chars-long'
  JWT_REFRESH_SECRET: 'placeholder-jwt-refresh-secret-min-32-chars-long'
  PAYSTACK_SECRET_KEY: 'sk_test_placeholder'
  STRIPE_SECRET_KEY: 'sk_test_placeholder'
  CLOUDINARY_CLOUD_NAME: 'placeholder'
  CLOUDINARY_API_KEY: 'placeholder'
  CLOUDINARY_API_SECRET: 'placeholder'
