apiVersion: v1
kind: Service
metadata:
  name: cartiva-api
  namespace: cartiva
  labels:
    app.kubernetes.io/name: cartiva-api
    app.kubernetes.io/part-of: cartiva-mall
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 5001
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: cartiva-api
