apiVersion: v1
kind: ServiceAccount
metadata:
  name: cartiva-api
  namespace: cartiva
  labels:
    app.kubernetes.io/name: cartiva-api
    app.kubernetes.io/part-of: cartiva-mall
    app.kubernetes.io/component: backend
automountServiceAccountToken: false
