apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cartiva-staging

resources:
  - ../../base

namePrefix: staging-

patches:
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
      name: cartiva-config
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: cartiva-ingress

commonLabels:
  environment: staging
